language: java
jdk:
  - oraclejdk8
install: /bin/true # skip gradle assemble
before_install:
  - wget https://releases.hashicorp.com/vault/0.3.1/vault_0.3.1_linux_386.zip
  - unzip vault_0.3.1_linux_386.zip
  - ./vault server -dev &
  - sleep 1
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault auth-enable app-id
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault write auth/app-id/map/app-id/test-app-id value=root display_name=foo
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault write auth/app-id/map/user-id/test-user-id value=test-app-id
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault write secret/keyOne value=secretNumberOne
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault write secret/keyTwo value=secretNumberTwo
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault write secret/keyThree value=secretNumberThree
script: gradlew check
